/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppSequenciasRouteImport } from './routes/_app.sequencias'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppExplorarRouteImport } from './routes/_app.explorar'
import { Route as AppDisparosRouteImport } from './routes/_app.disparos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as WidgetFormIdRouteImport } from './routes/widget.form.$id'
import { Route as ApiPublicWidgetSubmitRouteImport } from './routes/api.public.widget.submit'
import { Route as ApiPublicSequencesSentRouteImport } from './routes/api.public.sequences.sent'
import { Route as ApiPublicSequencesInboundRouteImport } from './routes/api.public.sequences.inbound'
import { Route as ApiPublicSequencesDueRouteImport } from './routes/api.public.sequences.due'
import { Route as ApiPublicEvolutionTestRouteImport } from './routes/api.public.evolution.test'
import { Route as ApiPublicEvolutionStatusRouteImport } from './routes/api.public.evolution.status'
import { Route as ApiPublicEvolutionQrRouteImport } from './routes/api.public.evolution.qr'
import { Route as ApiPublicEvolutionCreateRouteImport } from './routes/api.public.evolution.create'
import { Route as ApiPublicWidgetEmbedIdDotjsRouteImport } from './routes/api.public.widget.embed.$id[.]js'
import { Route as ApiPublicWidgetConfigIdRouteImport } from './routes/api.public.widget.config.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSequenciasRoute = AppSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorarRoute = AppExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppRoute,
} as any)
const AppDisparosRoute = AppDisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const WidgetFormIdRoute = WidgetFormIdRouteImport.update({
  id: '/widget/form/$id',
  path: '/widget/form/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetSubmitRoute = ApiPublicWidgetSubmitRouteImport.update({
  id: '/api/public/widget/submit',
  path: '/api/public/widget/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSequencesSentRoute = ApiPublicSequencesSentRouteImport.update({
  id: '/api/public/sequences/sent',
  path: '/api/public/sequences/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSequencesInboundRoute =
  ApiPublicSequencesInboundRouteImport.update({
    id: '/api/public/sequences/inbound',
    path: '/api/public/sequences/inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSequencesDueRoute = ApiPublicSequencesDueRouteImport.update({
  id: '/api/public/sequences/due',
  path: '/api/public/sequences/due',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionTestRoute = ApiPublicEvolutionTestRouteImport.update({
  id: '/api/public/evolution/test',
  path: '/api/public/evolution/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionStatusRoute =
  ApiPublicEvolutionStatusRouteImport.update({
    id: '/api/public/evolution/status',
    path: '/api/public/evolution/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionQrRoute = ApiPublicEvolutionQrRouteImport.update({
  id: '/api/public/evolution/qr',
  path: '/api/public/evolution/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvolutionCreateRoute =
  ApiPublicEvolutionCreateRouteImport.update({
    id: '/api/public/evolution/create',
    path: '/api/public/evolution/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetEmbedIdDotjsRoute =
  ApiPublicWidgetEmbedIdDotjsRouteImport.update({
    id: '/api/public/widget/embed/$id.js',
    path: '/api/public/widget/embed/$id.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetConfigIdRoute = ApiPublicWidgetConfigIdRouteImport.update({
  id: '/api/public/widget/config/$id',
  path: '/api/public/widget/config/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/disparos': typeof AppDisparosRoute
  '/explorar': typeof AppExplorarRoute
  '/inbox': typeof AppInboxRoute
  '/pipeline': typeof AppPipelineRoute
  '/sequencias': typeof AppSequenciasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/widget/form/$id': typeof WidgetFormIdRoute
  '/api/public/evolution/create': typeof ApiPublicEvolutionCreateRoute
  '/api/public/evolution/qr': typeof ApiPublicEvolutionQrRoute
  '/api/public/evolution/status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/evolution/test': typeof ApiPublicEvolutionTestRoute
  '/api/public/sequences/due': typeof ApiPublicSequencesDueRoute
  '/api/public/sequences/inbound': typeof ApiPublicSequencesInboundRoute
  '/api/public/sequences/sent': typeof ApiPublicSequencesSentRoute
  '/api/public/widget/submit': typeof ApiPublicWidgetSubmitRoute
  '/api/public/widget/config/$id': typeof ApiPublicWidgetConfigIdRoute
  '/api/public/widget/embed/$id.js': typeof ApiPublicWidgetEmbedIdDotjsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/disparos': typeof AppDisparosRoute
  '/explorar': typeof AppExplorarRoute
  '/inbox': typeof AppInboxRoute
  '/pipeline': typeof AppPipelineRoute
  '/sequencias': typeof AppSequenciasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/widget/form/$id': typeof WidgetFormIdRoute
  '/api/public/evolution/create': typeof ApiPublicEvolutionCreateRoute
  '/api/public/evolution/qr': typeof ApiPublicEvolutionQrRoute
  '/api/public/evolution/status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/evolution/test': typeof ApiPublicEvolutionTestRoute
  '/api/public/sequences/due': typeof ApiPublicSequencesDueRoute
  '/api/public/sequences/inbound': typeof ApiPublicSequencesInboundRoute
  '/api/public/sequences/sent': typeof ApiPublicSequencesSentRoute
  '/api/public/widget/submit': typeof ApiPublicWidgetSubmitRoute
  '/api/public/widget/config/$id': typeof ApiPublicWidgetConfigIdRoute
  '/api/public/widget/embed/$id.js': typeof ApiPublicWidgetEmbedIdDotjsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disparos': typeof AppDisparosRoute
  '/_app/explorar': typeof AppExplorarRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/sequencias': typeof AppSequenciasRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/widget/form/$id': typeof WidgetFormIdRoute
  '/api/public/evolution/create': typeof ApiPublicEvolutionCreateRoute
  '/api/public/evolution/qr': typeof ApiPublicEvolutionQrRoute
  '/api/public/evolution/status': typeof ApiPublicEvolutionStatusRoute
  '/api/public/evolution/test': typeof ApiPublicEvolutionTestRoute
  '/api/public/sequences/due': typeof ApiPublicSequencesDueRoute
  '/api/public/sequences/inbound': typeof ApiPublicSequencesInboundRoute
  '/api/public/sequences/sent': typeof ApiPublicSequencesSentRoute
  '/api/public/widget/submit': typeof ApiPublicWidgetSubmitRoute
  '/api/public/widget/config/$id': typeof ApiPublicWidgetConfigIdRoute
  '/api/public/widget/embed/$id.js': typeof ApiPublicWidgetEmbedIdDotjsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/disparos'
    | '/explorar'
    | '/inbox'
    | '/pipeline'
    | '/sequencias'
    | '/whatsapp'
    | '/widget/form/$id'
    | '/api/public/evolution/create'
    | '/api/public/evolution/qr'
    | '/api/public/evolution/status'
    | '/api/public/evolution/test'
    | '/api/public/sequences/due'
    | '/api/public/sequences/inbound'
    | '/api/public/sequences/sent'
    | '/api/public/widget/submit'
    | '/api/public/widget/config/$id'
    | '/api/public/widget/embed/$id.js'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/disparos'
    | '/explorar'
    | '/inbox'
    | '/pipeline'
    | '/sequencias'
    | '/whatsapp'
    | '/widget/form/$id'
    | '/api/public/evolution/create'
    | '/api/public/evolution/qr'
    | '/api/public/evolution/status'
    | '/api/public/evolution/test'
    | '/api/public/sequences/due'
    | '/api/public/sequences/inbound'
    | '/api/public/sequences/sent'
    | '/api/public/widget/submit'
    | '/api/public/widget/config/$id'
    | '/api/public/widget/embed/$id.js'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/disparos'
    | '/_app/explorar'
    | '/_app/inbox'
    | '/_app/pipeline'
    | '/_app/sequencias'
    | '/_app/whatsapp'
    | '/widget/form/$id'
    | '/api/public/evolution/create'
    | '/api/public/evolution/qr'
    | '/api/public/evolution/status'
    | '/api/public/evolution/test'
    | '/api/public/sequences/due'
    | '/api/public/sequences/inbound'
    | '/api/public/sequences/sent'
    | '/api/public/widget/submit'
    | '/api/public/widget/config/$id'
    | '/api/public/widget/embed/$id.js'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WidgetFormIdRoute: typeof WidgetFormIdRoute
  ApiPublicEvolutionCreateRoute: typeof ApiPublicEvolutionCreateRoute
  ApiPublicEvolutionQrRoute: typeof ApiPublicEvolutionQrRoute
  ApiPublicEvolutionStatusRoute: typeof ApiPublicEvolutionStatusRoute
  ApiPublicEvolutionTestRoute: typeof ApiPublicEvolutionTestRoute
  ApiPublicSequencesDueRoute: typeof ApiPublicSequencesDueRoute
  ApiPublicSequencesInboundRoute: typeof ApiPublicSequencesInboundRoute
  ApiPublicSequencesSentRoute: typeof ApiPublicSequencesSentRoute
  ApiPublicWidgetSubmitRoute: typeof ApiPublicWidgetSubmitRoute
  ApiPublicWidgetConfigIdRoute: typeof ApiPublicWidgetConfigIdRoute
  ApiPublicWidgetEmbedIdDotjsRoute: typeof ApiPublicWidgetEmbedIdDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequencias': {
      id: '/_app/sequencias'
      path: '/sequencias'
      fullPath: '/sequencias'
      preLoaderRoute: typeof AppSequenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorar': {
      id: '/_app/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AppExplorarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disparos': {
      id: '/_app/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof AppDisparosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/widget/form/$id': {
      id: '/widget/form/$id'
      path: '/widget/form/$id'
      fullPath: '/widget/form/$id'
      preLoaderRoute: typeof WidgetFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/submit': {
      id: '/api/public/widget/submit'
      path: '/api/public/widget/submit'
      fullPath: '/api/public/widget/submit'
      preLoaderRoute: typeof ApiPublicWidgetSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sequences/sent': {
      id: '/api/public/sequences/sent'
      path: '/api/public/sequences/sent'
      fullPath: '/api/public/sequences/sent'
      preLoaderRoute: typeof ApiPublicSequencesSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sequences/inbound': {
      id: '/api/public/sequences/inbound'
      path: '/api/public/sequences/inbound'
      fullPath: '/api/public/sequences/inbound'
      preLoaderRoute: typeof ApiPublicSequencesInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sequences/due': {
      id: '/api/public/sequences/due'
      path: '/api/public/sequences/due'
      fullPath: '/api/public/sequences/due'
      preLoaderRoute: typeof ApiPublicSequencesDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/test': {
      id: '/api/public/evolution/test'
      path: '/api/public/evolution/test'
      fullPath: '/api/public/evolution/test'
      preLoaderRoute: typeof ApiPublicEvolutionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/status': {
      id: '/api/public/evolution/status'
      path: '/api/public/evolution/status'
      fullPath: '/api/public/evolution/status'
      preLoaderRoute: typeof ApiPublicEvolutionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/qr': {
      id: '/api/public/evolution/qr'
      path: '/api/public/evolution/qr'
      fullPath: '/api/public/evolution/qr'
      preLoaderRoute: typeof ApiPublicEvolutionQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/create': {
      id: '/api/public/evolution/create'
      path: '/api/public/evolution/create'
      fullPath: '/api/public/evolution/create'
      preLoaderRoute: typeof ApiPublicEvolutionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/embed/$id.js': {
      id: '/api/public/widget/embed/$id.js'
      path: '/api/public/widget/embed/$id.js'
      fullPath: '/api/public/widget/embed/$id.js'
      preLoaderRoute: typeof ApiPublicWidgetEmbedIdDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/config/$id': {
      id: '/api/public/widget/config/$id'
      path: '/api/public/widget/config/$id'
      fullPath: '/api/public/widget/config/$id'
      preLoaderRoute: typeof ApiPublicWidgetConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisparosRoute: typeof AppDisparosRoute
  AppExplorarRoute: typeof AppExplorarRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSequenciasRoute: typeof AppSequenciasRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisparosRoute: AppDisparosRoute,
  AppExplorarRoute: AppExplorarRoute,
  AppInboxRoute: AppInboxRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSequenciasRoute: AppSequenciasRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WidgetFormIdRoute: WidgetFormIdRoute,
  ApiPublicEvolutionCreateRoute: ApiPublicEvolutionCreateRoute,
  ApiPublicEvolutionQrRoute: ApiPublicEvolutionQrRoute,
  ApiPublicEvolutionStatusRoute: ApiPublicEvolutionStatusRoute,
  ApiPublicEvolutionTestRoute: ApiPublicEvolutionTestRoute,
  ApiPublicSequencesDueRoute: ApiPublicSequencesDueRoute,
  ApiPublicSequencesInboundRoute: ApiPublicSequencesInboundRoute,
  ApiPublicSequencesSentRoute: ApiPublicSequencesSentRoute,
  ApiPublicWidgetSubmitRoute: ApiPublicWidgetSubmitRoute,
  ApiPublicWidgetConfigIdRoute: ApiPublicWidgetConfigIdRoute,
  ApiPublicWidgetEmbedIdDotjsRoute: ApiPublicWidgetEmbedIdDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
